/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    AConfigProvider: typeof import('@arco-design/web-vue')['ConfigProvider']
    ADivider: typeof import('@arco-design/web-vue')['Divider']
    ASelect: typeof import('@arco-design/web-vue')['Select']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ATypography: typeof import('@arco-design/web-vue')['Typography']
    ATypographyTitle: typeof import('@arco-design/web-vue')['TypographyTitle']
    Hello: typeof import('./src/components/Hello.vue')['default']
    IconAlignCenter: typeof import('@arco-design/web-vue/es/icon')['IconAlignCenter']
    IconAlignLeft: typeof import('@arco-design/web-vue/es/icon')['IconAlignLeft']
    IconAlignRight: typeof import('@arco-design/web-vue/es/icon')['IconAlignRight']
    IconBold: typeof import('@arco-design/web-vue/es/icon')['IconBold']
    IconCode: typeof import('@arco-design/web-vue/es/icon')['IconCode']
    IconH1: typeof import('@arco-design/web-vue/es/icon')['IconH1']
    IconH2: typeof import('@arco-design/web-vue/es/icon')['IconH2']
    IconH3: typeof import('@arco-design/web-vue/es/icon')['IconH3']
    IconH4: typeof import('@arco-design/web-vue/es/icon')['IconH4']
    IconH5: typeof import('@arco-design/web-vue/es/icon')['IconH5']
    IconH6: typeof import('@arco-design/web-vue/es/icon')['IconH6']
    IconHighlight: typeof import('@arco-design/web-vue/es/icon')['IconHighlight']
    IconItalic: typeof import('@arco-design/web-vue/es/icon')['IconItalic']
    IconOrderedList: typeof import('@arco-design/web-vue/es/icon')['IconOrderedList']
    IconQuote: typeof import('@arco-design/web-vue/es/icon')['IconQuote']
    IconRedo: typeof import('@arco-design/web-vue/es/icon')['IconRedo']
    IconStrikethrough: typeof import('@arco-design/web-vue/es/icon')['IconStrikethrough']
    IconUndo: typeof import('@arco-design/web-vue/es/icon')['IconUndo']
    IconUnorderedList: typeof import('@arco-design/web-vue/es/icon')['IconUnorderedList']
    ParentSelect: typeof import('./src/components/ParentSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TiptapEditor: typeof import('./src/components/TiptapEditor.vue')['default']
  }
}
